# Generated by Django 3.2.9 on 2021-11-21 14:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_genre',
            field=models.JSONField(default=accounts.models.default_somemodel_dict),
        ),
    ]
